# Generated by Django 2.2.4 on 2019-09-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menurow2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuRow2',
            new_name='Cake',
        ),
    ]
